version: "3.7"
services:
  app:
    image: sample-project
    restart: always
    build: .
    ports:
      - 8000:8000
    env_file: ./.env
    depends_on:
      - mongo
      - nginx
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    # For local dev only
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html/dist
      - ./client/public:/usr/share/nginx/html/public
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    env_file: ./.env
    volumes:
      - ./mongo_data:/data/db
