version: "3.7"
services:
  app:
    image: app:latest
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    depends_on:
      - mongo
    volumes:
      - static-content:/opt/app/client
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static-content:/var/www/html
      # - static-assets:/usr/share/nginx/html
      # - ../client/dist:/usr/share/nginx/html/dist
      # - ../client/public:/usr/share/nginx/html/public
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    env_file: ../.env
    volumes:
      - ./mongo_data:/data/db
volumes:
  static-content:
