version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '../client/dist:/usr/share/nginx/html/dist'
      - '../client/public:/usr/share/nginx/html/public'
